service: Eootm
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  httpApi:
    cors: true
    authorizers:
      serviceAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.${self:provider.region}.amazonaws.com/${self:provider.environment.user_pool_id}
        audience: 
          - ${self:provider.environment.client_id}
  region: ap-south-1
  stage: dev
  timeout: 10
  memorySize: 128
  environment:
    
    DYNAMODB_TABLE: EOOMT
    REGION_NAME: ${self:provider.region}
    user_pool_id: ap-south-1_sQeBGTxl8
    client_id: 48hko2q1qsd36p6d3kcrla334j


  iam:
      role:
        statements:
          - Effect: 'Allow'
            Resource: '*'
            Action: 's3:*'
          - Effect: Allow
            Action:
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
            Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

          - Effect: Allow
            Action:
              - cognito-identity:*
              - cognito-sync:*
              - cognito-idp:*
              - lambda:*
            Resource: "arn:aws:cognito-idp:ap-south-1:377944167346:userpool/ap-south-1_sQeBGTxl8"  


package: 
  patterns:
    - '!front-end/**'

functions:

  get_all_task_types:
    handler: task-type/handler.get_all_task_types  
    layers:
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-p38-requests-html:10
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-python38-passlib:1
    events:
      - httpApi:
          path: /task-type/getAll
          method: get
          authorizer: 
            name: serviceAuthorizer        

  emp_by_task_type:
    handler: employees/handler.emp_by_task_type  
    layers:
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-p38-requests-html:10
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-python38-passlib:1
    events:
      - httpApi:
          path: /employees/emp
          method: get
          authorizer: 
            name: serviceAuthorizer 

  add_new_task:
    handler: task-list/handler.add_new_task  
    layers:
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-p38-requests-html:10
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-python38-passlib:1
    events:
      - httpApi:
          path: /addTask
          method: post
          authorizer: 
            name: serviceAuthorizer                             
  
  add_new_task_type:
    handler: task-type/handler.add_new_task_type  
    layers:
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-p38-requests-html:10
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-python38-passlib:1
    events:
      - httpApi:
          path: /addTaskType
          method: post
          authorizer: 
            name: serviceAuthorizer      


  get_all_employees:
    handler: employees/handler.get_all_employees  
    layers:
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-p38-requests-html:10
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-python38-passlib:1
    events:
      - httpApi:
          path: /allemp
          method: get
          authorizer: 
            name: serviceAuthorizer    

  create_new_employee:
    handler: employees/handler.create_new_employee  
    layers:
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-p38-requests-html:10
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-python38-passlib:1
    events:
      - httpApi:
          path: /newemp
          method: post
          authorizer: 
            name: serviceAuthorizer   

  get_tasks_by_tasktype:           
    handler: task-list/handler.get_tasks_by_tasktype  
    layers:
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-p38-requests-html:10
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-python38-passlib:1
    events:
      - httpApi:
          path: /tasks_by_tasktype/{type}
          method: get
          authorizer: 
            name: serviceAuthorizer   
  
  update_tasktype:
    handler: task-type/handler.update_tasktype  
    layers:
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-p38-requests-html:10
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-python38-passlib:1
    events:
      - httpApi:
          path: /update_tasktype
          method: put
          authorizer: 
            name: serviceAuthorizer   
  
  get_all_users:

    handler: employees/handler.get_all_users
    layers:
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-p38-requests-html:10
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-python38-passlib:1
    events:
      - httpApi:
          path: /get_all_users
          method: get
          authorizer: 
            name: serviceAuthorizer 
  delete_user:
    handler: employees/handler.deleteUser  
    layers:
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-p38-requests-html:10
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-python38-passlib:1
    events:
      - httpApi:
          path: /delete_user/{user_name}
          method: delete
          authorizer: 

            name: serviceAuthorizer      
  
  add_new_tasktype_to_employee:
    handler: task-type/handler.add_new_tasktype_to_employee 
    layers:
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-p38-requests-html:10
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-python38-passlib:1
    events:
      - httpApi:
          path: /add_new_tasktype_to_employee 
          method: post
          authorizer: 
            name: serviceAuthorizer      
  
  update_user:
    handler: employees/handler.updateUser  
    layers:
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-p38-requests-html:10
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-python38-passlib:1
    events:
      - httpApi:
          path: /update_user
          method: put
          authorizer: 
            name: serviceAuthorizer      
  
  get_all_tasktype_assigned_users:
    handler: employees/handler.get_all_tasktype_assigned_users  
    layers:
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-p38-requests-html:10
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-python38-passlib:1
    events:
      - httpApi:
          path: /get_all_tasktype_assigned_users
          method: get
          authorizer: 
            name: serviceAuthorizer      
 
  create_user:
    handler: employees/handler.create_user  
    layers:
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-p38-requests-html:10
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-python38-passlib:1
    events:
      - httpApi:
          path: /create_user
          method: post
          authorizer: 
            name: serviceAuthorizer
  verify_user:
    handler: employees/handler.verify_user  
    layers:
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-p38-requests-html:10
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-python38-passlib:1
    events:
      - httpApi:
          path: /verify_user
          method: post
          authorizer: 
            name: serviceAuthorizer
  
  update_completion_status:
    handler: task-list/handler.update_completion_status  
    layers:
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-p38-requests-html:10
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-python38-passlib:1
    events:
      - httpApi:
          path: /update_completion_status
          method: put
          authorizer: 
            name: serviceAuthorizer

  get_user_tasks:
    handler: task-list/handler.get_user_tasks  
    layers:
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-p38-requests-html:10
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-python38-passlib:1
    events:
      - httpApi:
          path: /get_user_tasks/{empID}
          method: get
          authorizer: 
            name: serviceAuthorizer


  generate_random_password:
    handler: employees/handler.generate_random_password      
    layers:
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-p38-requests-html:10
     - arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-python38-passlib:1   
plugins:
  - serverless-python-requirements


